package mx.com.mentoringit.entities;
// Generated 20-jun-2016 21:40:30 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Banco generated by hbm2java
 */
public class Banco implements java.io.Serializable {

	private Integer idBanco;
	private String nombre;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);

	public Banco() {
	}

	public Banco(String nombre) {
		this.nombre = nombre;
	}

	public Banco(String nombre, Set<Cliente> clientes) {
		this.nombre = nombre;
		this.clientes = clientes;
	}

	public Integer getIdBanco() {
		return this.idBanco;
	}

	public void setIdBanco(Integer idBanco) {
		this.idBanco = idBanco;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

}
