package mx.com.mentoringit.entities;
// Generated 20-jun-2016 21:40:30 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta implements java.io.Serializable {

	private Integer idCuenta;
	private Cliente cliente;
	private Tipocuenta tipocuenta;
	private int numeroCuenta;
	private Set<Movimiento> movimientos = new HashSet<Movimiento>(0);

	public Cuenta() {
	}

	public Cuenta(Cliente cliente, Tipocuenta tipocuenta, int numeroCuenta) {
		this.cliente = cliente;
		this.tipocuenta = tipocuenta;
		this.numeroCuenta = numeroCuenta;
	}

	public Cuenta(Cliente cliente, Tipocuenta tipocuenta, int numeroCuenta, Set<Movimiento> movimientos) {
		this.cliente = cliente;
		this.tipocuenta = tipocuenta;
		this.numeroCuenta = numeroCuenta;
		this.movimientos = movimientos;
	}

	public Integer getIdCuenta() {
		return this.idCuenta;
	}

	public void setIdCuenta(Integer idCuenta) {
		this.idCuenta = idCuenta;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Tipocuenta getTipocuenta() {
		return this.tipocuenta;
	}

	public void setTipocuenta(Tipocuenta tipocuenta) {
		this.tipocuenta = tipocuenta;
	}

	public int getNumeroCuenta() {
		return this.numeroCuenta;
	}

	public void setNumeroCuenta(int numeroCuenta) {
		this.numeroCuenta = numeroCuenta;
	}

	public Set<Movimiento> getMovimientos() {
		return this.movimientos;
	}

	public void setMovimientos(Set<Movimiento> movimientos) {
		this.movimientos = movimientos;
	}

}
