package mx.com.mentoringit.entities;
// Generated 20-jun-2016 21:40:30 by Hibernate Tools 4.3.1.Final

/**
 * Login generated by hbm2java
 */
public class Login implements java.io.Serializable {

	private Integer idUsuario;
	private Perfil perfil;
	private String nombre;
	private String apaterno;
	private String amaterno;
	private String usuario;
	private String password;

	public Login() {
	}

	public Login(Perfil perfil, String nombre, String usuario, String password) {
		this.perfil = perfil;
		this.nombre = nombre;
		this.usuario = usuario;
		this.password = password;
	}

	public Login(Perfil perfil, String nombre, String apaterno, String amaterno, String usuario, String password) {
		this.perfil = perfil;
		this.nombre = nombre;
		this.apaterno = apaterno;
		this.amaterno = amaterno;
		this.usuario = usuario;
		this.password = password;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApaterno() {
		return this.apaterno;
	}

	public void setApaterno(String apaterno) {
		this.apaterno = apaterno;
	}

	public String getAmaterno() {
		return this.amaterno;
	}

	public void setAmaterno(String amaterno) {
		this.amaterno = amaterno;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
