package mx.com.mentoringit.entities;
// Generated 20-jun-2016 21:40:30 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Movimiento generated by hbm2java
 */
public class Movimiento implements java.io.Serializable {

	private Integer idMovimiento;
	private Cuenta cuenta;
	private Tipomovimiento tipomovimiento;
	private Date fecha;
	private BigDecimal monto;

	public Movimiento() {
	}

	public Movimiento(Cuenta cuenta, Tipomovimiento tipomovimiento, Date fecha, BigDecimal monto) {
		this.cuenta = cuenta;
		this.tipomovimiento = tipomovimiento;
		this.fecha = fecha;
		this.monto = monto;
	}

	public Integer getIdMovimiento() {
		return this.idMovimiento;
	}

	public void setIdMovimiento(Integer idMovimiento) {
		this.idMovimiento = idMovimiento;
	}

	public Cuenta getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(Cuenta cuenta) {
		this.cuenta = cuenta;
	}

	public Tipomovimiento getTipomovimiento() {
		return this.tipomovimiento;
	}

	public void setTipomovimiento(Tipomovimiento tipomovimiento) {
		this.tipomovimiento = tipomovimiento;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

}
