package mx.com.mentoringit.entities;
// Generated 20-jun-2016 21:40:30 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Tipocuenta generated by hbm2java
 */
public class Tipocuenta implements java.io.Serializable {

	private Integer idTipoCuenta;
	private String nombre;
	private Set<Cuenta> cuentas = new HashSet<Cuenta>(0);

	public Tipocuenta() {
	}

	public Tipocuenta(String nombre) {
		this.nombre = nombre;
	}

	public Tipocuenta(String nombre, Set<Cuenta> cuentas) {
		this.nombre = nombre;
		this.cuentas = cuentas;
	}

	public Integer getIdTipoCuenta() {
		return this.idTipoCuenta;
	}

	public void setIdTipoCuenta(Integer idTipoCuenta) {
		this.idTipoCuenta = idTipoCuenta;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Cuenta> getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Set<Cuenta> cuentas) {
		this.cuentas = cuentas;
	}

}
