package mx.com.mentoringit.entities;
// Generated 20-jun-2016 21:40:30 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Tipomovimiento generated by hbm2java
 */
public class Tipomovimiento implements java.io.Serializable {

	private Integer idTipoMovimiento;
	private String nombre;
	private Set<Movimiento> movimientos = new HashSet<Movimiento>(0);

	public Tipomovimiento() {
	}

	public Tipomovimiento(String nombre) {
		this.nombre = nombre;
	}

	public Tipomovimiento(String nombre, Set<Movimiento> movimientos) {
		this.nombre = nombre;
		this.movimientos = movimientos;
	}

	public Integer getIdTipoMovimiento() {
		return this.idTipoMovimiento;
	}

	public void setIdTipoMovimiento(Integer idTipoMovimiento) {
		this.idTipoMovimiento = idTipoMovimiento;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Movimiento> getMovimientos() {
		return this.movimientos;
	}

	public void setMovimientos(Set<Movimiento> movimientos) {
		this.movimientos = movimientos;
	}

}
